In [241]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [242]:
df = pd.read_csv("/content/Titanic-Dataset.csv")

In [243]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [244]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [245]:
df.shape

(891, 12)

In [246]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [247]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [248]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

## Insights
- PassengerId is unique for every value
- Name is unique for every value

**These columns are of no use, hence has to be removed.**

In [249]:
df = df.drop(columns= ['PassengerId', 'Name'], axis = 1)

In [250]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [251]:
print(df.shape)

(891, 10)

In [252]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    object
 7   Fare      891 non-null    float64
 8   Cabin     204 non-null    object
 9   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 69.7+ KB

In [253]:
df['Sex'] = df['Sex'].map({'male':0,'female':1})

In [254]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Ticket    891 non-null    object
 7   Fare      891 non-null    float64
 8   Cabin     204 non-null    object
 9   Embarked  889 non-null    object
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

Ticker does not affect whether the person would survive in the accident or not. So, the column has to be removed.

In [255]:
df = df.drop(columns=['Ticket', 'Fare'], axis =1)

In [256]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [257]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch Cabin Embarked
0         0       3    0  22.0      1      0   NaN        S
1         1       1    1  38.0      1      0   C85        C
2         1       3    1  26.0      0      0   NaN        S
3         1       1    1  35.0      1      0  C123        S
4         0       3    0  35.0      0      0   NaN        S

In [258]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Cabin     204 non-null    object
 7   Embarked  889 non-null    object
dtypes: float64(1), int64(5), object(2)
memory usage: 55.8+ KB

In [259]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Cabin       687
Embarked      2
dtype: int64

- The two rows with missing embarked can be removed.
- Since Cabin has a lot of missin values, the column can be dropped and will not affect the dataset much.
- The number of missing entries in the Age column will be determined latter after that.

In [260]:
df = df.drop(columns= ['Cabin'], axis=1)

In [261]:
df.shape

(891, 7)

In [262]:
df['Embarked'].isna().sum()

2

In [263]:
df.shape

(891, 7)

In [264]:
df = df.dropna(subset='Embarked')

In [265]:
df.shape

(889, 7)

In [266]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch Embarked
0         0       3    0  22.0      1      0        S
1         1       1    1  38.0      1      0        C
2         1       3    1  26.0      0      0        S
3         1       1    1  35.0      1      0        S
4         0       3    0  35.0      0      0        S

In [267]:
df.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Embarked      0
dtype: int64

In [268]:
# df['Age'] = df['Age'].fillna(value=df['Age'].mode().values[0])
df['Age'] = df['Age'].fillna(value=int(df['Age'].mean()))
# int(df['Age'].mean())

<ipython-input-268-ee2c6fc27c56>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].fillna(value=int(df['Age'].mean()))

In [269]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    int64
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64
 5   Parch     889 non-null    int64
 6   Embarked  889 non-null    object
dtypes: float64(1), int64(5), object(1)
memory usage: 55.6+ KB

In [270]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [271]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [272]:
df['Embarked'] = df['Embarked'].map({'S':0,'C':1,'Q':2})

In [273]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  889 non-null    int64
 1   Pclass    889 non-null    int64
 2   Sex       889 non-null    int64
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64
 5   Parch     889 non-null    int64
 6   Embarked  889 non-null    int64
dtypes: float64(1), int64(6)
memory usage: 55.6 KB

In [274]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    0  22.0      1      0         0
1         1       1    1  38.0      1      0         1
2         1       3    1  26.0      0      0         0
3         1       1    1  35.0      1      0         0
4         0       3    0  35.0      0      0         0

In [275]:
y = df['Survived']
x = df.drop(columns =['Survived'], axis = 1)

In [276]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    889 non-null    int64
 1   Sex       889 non-null    int64
 2   Age       889 non-null    float64
 3   SibSp     889 non-null    int64
 4   Parch     889 non-null    int64
 5   Embarked  889 non-null    int64
dtypes: float64(1), int64(5)
memory usage: 48.6 KB

In [277]:
# prompt: Using dataframe x: scalling of data

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [278]:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.1, random_state = 48)

In [279]:
x_test.shape, y_test.shape

((89, 6), (89,))

In [280]:
x_test.shape

(89, 6)

In [281]:
from sklearn.tree import DecisionTreeClassifier
# from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

In [282]:
from sklearn.preprocessing import StandardScaler

x

array([[ 0.82520863, -0.73534203, -0.57964299,  0.43135024, -0.47432585,
        -0.56968402],
       [-1.57221121,  1.35991138,  0.65458337,  0.43135024, -0.47432585,
         1.00313924],
       [ 0.82520863,  1.35991138, -0.2710864 , -0.47519908, -0.47432585,
        -0.56968402],
       ...,
       [ 0.82520863,  1.35991138, -0.03966896,  0.43135024,  2.00611934,
        -0.56968402],
       [-1.57221121, -0.73534203, -0.2710864 , -0.47519908, -0.47432585,
         1.00313924],
       [ 0.82520863, -0.73534203,  0.19174848, -0.47519908, -0.47432585,
         2.5759625 ]])

In [283]:
from sklearn.metrics import accuracy_score

In [284]:
# models = {
#     "DecisionTreeClassifier": DecisionTreeClassifier(),
#     "KNeighborsClassifier": KNeighborsClassifier()
# }
# model_list = []
# r2_list=[]

# for i in range(len(list(models))):
#   model = list(models.values())[i]
#   model.fit(x_train,y_train)

#   pred = model.predict(x_test)
dec_model = DecisionTreeClassifier()
dec_model.fit(x_train, y_train)

train_dec_pred = dec_model.predict(x_train)
test_dec_pred = dec_model.predict(x_test)

print(f"The accuracy of the training prediction is {accuracy_score(y_train, train_dec_pred)}")
print(f"The accuracy of the test prediction is {accuracy_score(y_test, test_dec_pred)}")

The accuracy of the training prediction is 0.94
The accuracy of the test prediction is 0.7640449438202247

In [285]:
knn_model = KNeighborsClassifier()

knn_model.fit(x_train, y_train)

train_knn_pred = knn_model.predict(x_train)
test_knn_pred = knn_model.predict(x_test)
print(f"The accuracy of the training prediction is {accuracy_score(y_train, train_knn_pred)}")
print(f"The accuracy of the test prediction is {accuracy_score(y_test, test_knn_pred)}")

The accuracy of the training prediction is 0.84875
The accuracy of the test prediction is 0.797752808988764

In [286]:
from sklearn.linear_model import LinearRegression

lin_model = LinearRegression()

lin_model.fit(x_train, y_train)

train_lin_pred = lin_model.predict(x_train)
test_lin_pred = lin_model.predict(x_test)
# print(train_lin_pred)
# print(f"The accuracy of the training prediction is {accuracy_score(y_train, train_lin_pred)}")
# print(f"The accuracy of the test prediction is {accuracy_score(y_test, test_lin_pred)}")

In [287]:
from sklearn.ensemble import RandomForestClassifier

ran_model = RandomForestClassifier()

ran_model.fit(x_train, y_train)
train_ran_pred = ran_model.predict(x_train)
test_ran_pred = ran_model.predict(x_test)

print(f"The accuracy of the training prediction is {accuracy_score(y_train, train_knn_pred)}")
print(f"The accuracy of the test prediction is {accuracy_score(y_test, test_knn_pred)}")

The accuracy of the training prediction is 0.84875
The accuracy of the test prediction is 0.797752808988764